version: 2

sources:
  - name: nextbike-404713
    description: raw data from nextbike api
    database: nextbike-404713
    schema: nextbike
    tables:
      - name: Live3
        description: 'nextbike api data'
      - name: Weather_Data  # Add the new table here
        description: 'weather data'
